/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.hfoss.contactapp;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int BtnSave=0x7f050008;
        public static final int labelAddress=0x7f050002;
        public static final int labelHome=0x7f050006;
        public static final int labelMobile=0x7f050004;
        public static final int labelName=0x7f050000;
        public static final int name=0x7f050009;
        public static final int phonenumber=0x7f05000a;
        public static final int textAddress=0x7f050003;
        public static final int textHome=0x7f050007;
        public static final int textMobile=0x7f050005;
        public static final int textName=0x7f050001;
    }
    public static final class layout {
        public static final int contact_edit=0x7f030000;
        public static final int contact_list=0x7f030001;
        public static final int contact_row=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int label_address=0x7f040005;
        public static final int label_name=0x7f040004;
        public static final int menu_delete=0x7f040003;
        public static final int menu_insert=0x7f040002;
        public static final int no_notes=0x7f040001;
    }
}
